export const API_KEY = "687697daf00f72e0a7e20cf9f55a44ec";
export const LANGUAGE_TOOLTIP_CHANGE = "LANGUAGE_TOOLTIP_CHANGE";
export const FILTER_CHANGE = "FILTER_CHANGE";
export const PAGINATION_CHANGE = "PAGINATION_CHANGE";
export const SEARCH_CHANGE = "SEARCH_CHANGE";
export const RESET_FILTERS = "RESET_FILTERS";
export const CREW_OPEN_CHANGE = "CREW_OPEN_CHANGE";
export const SET_SEARCH_PAGE = "SET_SEARCH_PAGE";